// constants
export const GET_COLORS = 'GET_COLORS';
export const ADD_COLOR = 'ADD_COLOR';
export const DELETE_COLOR = 'DELETE_COLOR';
export const SET_COLORS = 'SET_COLORS';
export const SWAP_COLORS = 'SWAP_COLORS';

export const GET_COLORSCHEMES = 'GET_COLORSCHEMES';
export const SAVE_COLORSCHEME = 'SAVE_COLORSCHEME';

export const GET_COLORCONFIG = 'GET_COLORCONFIG';
export const SET_BGCOLOR = 'SET_BGCOLOR';
export const SET_TEXTCOLOR = 'SET_TEXTCOLOR';

export const GET_DATASETS = 'GET_DATASETS';
export const ADD_DATASETS = 'ADD_DATASETS';

export const GET_CHARTS = 'GET_CHARTS';
export const ADD_CHARTS = 'ADD_CHARTS';
export const DELETE_CHART = 'DELETE_CHART';
export const UPDATE_CHART = 'UPDATE_CHART';
export const RECOLORING_CHARTS = 'RECOLORING_CHARTS';
export const RECOLORED_CHARTS = 'RECOLORED_CHARTS';
export const LOADING_EXAMPLE = 'LOADING_EXAMPLE';
export const LOADED_EXAMPLE = 'LOADED_EXAMPLE';

export const SET_PARAM = 'SET_PARAM';
export const GET_PARAM = 'GET_PARAM';

export const GET_EXAMPLES = 'GET_EXAMPLES';
export const GET_MVCOLORENCODINGS = 'GET_MVCOLORENCODINGS';
export const GET_MVCONCEPTGROUPINGS = 'GET_MVCONCEPTGROUPINGS';

export const GET_COLORENCODINGS = 'GET_COLORENCODINGS';

export const GET_RANGECOLORS = 'GET_RANGECOLORS';
export const UPDATE_RANGECOLOR = 'UPDATE_RANGECOLOR';
export const SWAP_RANGECOLORS = 'SWAP_RANGECOLORS';